zephyrproject-rtos/hal_renesas

- .gitignore
- smartbond/CMakeLists.txt
- smartbond/cmac/CMakeLists.txt
- smartbond/cmac/libcmac/cmac_img.ld
- smartbond/cmac/libcmac/cmac_ram.ld
- smartbond/cmac/mbox.c
- smartbond/cmac/mbox.h
- smartbond/cmac/rand.c
- smartbond/cmac/rand.h
- smartbond/cmac/shm.c
- smartbond/cmac/shm.h
- zephyr/blobs/license.txt
- zephyr/module.yml
This adds implementation of shared memory communication with CMAC.
> Add CMAC shared memory handlers and binary

- smartbond/da1469x_hal/da1469x_lcdc.c
- smartbond/da1469x_hal/da1469x_lcdc.h
This commit adds updates for the LCDC API.
> hal: renesas: LCD controller driver API.

- CMakeLists.txt
Updates family name for hwmv2 changes
> hal: renesas: Update for hwmv2

- smartbond/da1469x_hal/da1469x_sleep.c
> da1469x_sleep: remove SW trigger PDC entry

- drivers/ra/CMakeLists.txt
- drivers/ra/README
- drivers/ra/fsp/inc/api/r_can_api.h
- drivers/ra/fsp/inc/instances/r_canfd.h
- drivers/ra/fsp/src/r_canfd/r_canfd.c
- zephyr/ra/ra_cfg/fsp_cfg/r_canfd_cfg.h
Add fsp hal layer support for canfd module
> hal: ra: Initial support for canfd

- drivers/ra/CMakeLists.txt
- drivers/ra/fsp/inc/api/r_usb_device_api.h
- drivers/ra/fsp/inc/instances/r_usb_device.h
- drivers/ra/fsp/src/r_usb_device/r_usb_device.c
- zephyr/ra/ra_cfg/fsp_cfg/r_usb_device_cfg.h
First commit to support USB device HAL driver
> hal: renesas: ra: add support for r_usb_device

- drivers/ra/CMakeLists.txt
First commit to support r_sce on SCE7 HWIP
> hal: renesas: ra: initial support for SCE7

- drivers/ra/CMakeLists.txt
Initial support r_sce on SCE5 HWIP
> hal: renesas: ra: initial support for SCE5

- drivers/ra/CMakeLists.txt
Initial support r_sce on TRNG HWIP
> hal: renesas: ra: initial support for TRNG

- drivers/rz/CMakeLists.txt
- drivers/rz/fsp/inc/api/r_adc_api.h
- drivers/rz/fsp/inc/instances/rzg/r_adc_c.h
- drivers/rz/fsp/src/rzg/r_adc_c/r_adc_c.c
- zephyr/rz/rz_cfg/fsp_cfg/rzg/r_adc_c_cfg.h
> hal: renesas: rz: Initial support for ADC

- drivers/rz/CMakeLists.txt
- drivers/rz/fsp/inc/api/r_timer_api.h
- drivers/rz/fsp/inc/instances/rzg/r_gtm.h
- drivers/rz/fsp/src/rzg/r_gtm/r_gtm.c
- zephyr/rz/rz_cfg/fsp_cfg/rzg/r_gtm_cfg.h
Initial HAL support for System Timer and Counter
> hal: renesas: rz: Initial support for System Timer and Counter

- drivers/ra/CMakeLists.txt
Initial support r_sce on SCE9 HWIP
> hal: renesas: ra: initial support for SCE9

- drivers/rz/CMakeLists.txt
- drivers/rz/fsp/inc/api/r_can_api.h
- drivers/rz/fsp/inc/instances/rzg/r_canfd.h
- drivers/rz/fsp/src/rzg/r_canfd/r_canfd.c
- zephyr/rz/rz_cfg/fsp_cfg/rzg/r_canfd_cfg.h
> hal: renesas: rz: Initial support for CAN

- drivers/ra/CMakeLists.txt
- drivers/ra/fsp/inc/api/r_dac_api.h
- drivers/ra/fsp/inc/instances/r_dac.h
- drivers/ra/fsp/src/r_dac/r_dac.c
- zephyr/ra/ra_cfg/fsp_cfg/r_dac_cfg.h
Initial support r_dac on DAC HWIP
> hal: renesas: ra: Initial support for DAC driver

- drivers/ra/fsp/src/bsp/mcu/ra4e1/bsp_feature.h
Support USBFS device for Renesas RA4E1
> hal: renesas: ra: update BSP features macro for RA4E1

- drivers/rz/CMakeLists.txt
- drivers/rz/fsp/inc/api/r_spi_api.h
- drivers/rz/fsp/inc/instances/rzg/r_dmac_b.h
- drivers/rz/fsp/inc/instances/rzg/r_rspi.h
- drivers/rz/fsp/src/rzg/CMakeLists.txt
- drivers/rz/fsp/src/rzg/r_dmac_b/r_dmac_b.c
- drivers/rz/fsp/src/rzg/r_rspi/r_rspi.c
- zephyr/rz/rz_cfg/fsp_cfg/rzg/r_dmac_b_cfg.h
- zephyr/rz/rz_cfg/fsp_cfg/rzg/r_rspi_cfg.h
> hal: renesas: rz: Initial support for SPI

- drivers/ra/CMakeLists.txt
- drivers/ra/README
- drivers/ra/fsp/inc/api/r_usb_api.h
- drivers/ra/fsp/inc/api/r_usb_host_api.h
- drivers/ra/fsp/inc/instances/r_usb_host.h
- drivers/ra/fsp/src/r_usb_host/r_usb_host.c
- zephyr/ra/ra_cfg/fsp_cfg/r_usb_host_cfg.h
First commit to support r_usb_host on USBHS module
> hal: renesas: ra: initial support for r_usb_host

- drivers/ra/README
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra2a1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra2l1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4e1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4e2/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4l1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4m1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4m2/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4m3/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4w1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6e1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6e2/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m2/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m3/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m4/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m5/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8d1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8m1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8t1/bsp_mcu_family_cfg.h
Modify BSP_PRV_IELS_ENUM to use CONCAT instead of "##"
> hal: renesas: ra: Modify BSP_PRV_IELS_ENUM for build process

- drivers/ra/CMakeLists.txt
- drivers/ra/fsp/inc/api/r_wdt_api.h
- drivers/ra/fsp/inc/instances/r_wdt.h
- drivers/ra/fsp/src/bsp/mcu/all/bsp_group_irq.c
- drivers/ra/fsp/src/r_wdt/r_wdt.c
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra2a1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra2l1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4e1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4e2/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4l1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4m2/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4m3/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4w1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6e1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6e2/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m2/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m3/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m4/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m5/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8d1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8m1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8t1/bsp_mcu_family_cfg.h
- zephyr/ra/ra_cfg/fsp_cfg/r_wdt_cfg.h
- Add NMI_Handler definition
- Add support for r_wdt
> hal: renesas: ra: add support for r_wdt

- drivers/ra/CMakeLists.txt
- drivers/ra/README
- drivers/ra/fsp/inc/api/r_comparator_api.h
- drivers/ra/fsp/inc/instances/r_acmphs.h
- drivers/ra/fsp/src/r_acmphs/r_acmphs.c
- zephyr/ra/ra_cfg/fsp_cfg/r_acmphs_cfg.h
Initial support for ACMPHS driver with r_acmphs in Renesas HAL
> hal: renesas: ra: Initial support for ACMPHS driver

- zephyr/ra/CMakeLists.txt
- zephyr/ra/portable/inc/rp_agt.h
- zephyr/ra/portable/src/rp_agt/rp_agt.c
- Initial support for rp_agt
- Add aditional support for AGT CompareMatch function
> hal: renesas: ra: add portable implementation for r_agt

- drivers/ra/CMakeLists.txt
- drivers/ra/fsp/inc/api/r_i3c_api.h
- drivers/ra/fsp/inc/instances/r_i3c.h
- drivers/ra/fsp/src/r_i3c/r_i3c.c
- zephyr/ra/CMakeLists.txt
- zephyr/ra/portable/inc/rp_i3c.h
- zephyr/ra/portable/src/rp_i3c/rp_i3c.c
- zephyr/ra/ra_cfg/fsp_cfg/r_i3c_cfg.h
Initial support for r_i3c
Signed-off-by: Ta Minh Nhat <nhat-minh.ta.yn@bp.renesas.com>
> hal: renesas: ra: initial support for r_i3c

- drivers/ra/CMakeLists.txt
- drivers/ra/fsp/inc/api/r_capture_api.h
- drivers/ra/fsp/inc/instances/r_ceu.h
- drivers/ra/fsp/src/r_ceu/r_ceu.c
- zephyr/ra/ra_cfg/fsp_cfg/r_ceu_cfg.h
> hal: renesas: ra: initial support for CEU driver

- drivers/ra/README
Update FSP 6.0.0 commit id for README
> hal: renesas: ra: Update FSP commit id

- drivers/ra/CMakeLists.txt
- drivers/ra/fsp/inc/api/r_ipc_api.h
- drivers/ra/fsp/inc/instances/r_ipc.h
- drivers/ra/fsp/src/r_ipc/r_ipc.c
- zephyr/ra/ra_cfg/fsp_cfg/r_ipc_cfg.h
Add support Renesas RA `r_ipc` HWIP
> hal: renesas: ra: Add support r_ipc HWIP
