smartbond/da1469x_hal/da1469x_clock.c, smartbond/da1469x_hal/da1469x_pd.c
- Condition was incorrect resulting in assertion failure.
- Dynamic memory allocation remove from pd ode. It was used in PRE_KERNEL_1 stage where heap is not available yet
=> hal: renesas: Fix assert condition in xtal32m switch

smartbond/da1469x_hal/da1469x_clock.c
This commit fixes bad assertion expressions in clock driver.
=> hal: renesas: clock assertion fixes

smartbond/da1469x_hal/CMakeLists.txt, smartbond/da1469x_hal/da1469x_qspic.c, smartbond/da1469x_hal/da1469x_qspic.h
This commit adds API for QSPIx controller. Currently, this is intended to drive PSRAM memory devices. In the future, the API will be extended so it can fully support NOR/Flash memory devices, as well.
=> hal: renesas: QSPICx driver API.

smartbond/da1469x_hal/CMakeLists.txt, smartbond/da1469x_hal/da1469x_sleep.c, smartbond/da1469x_hal/da1469x_sleep.h, smartbond/da1469x_hal/da1469x_sleep_asm.S
This adds startup code that handles wakeup from deep sleep (CPU-off)
da1469x_sleep() function is intended to be called from OS function that wants to go to sleep.
When function finishes basic system functionality is restored if system went to sleep (clocks, GPIO etc.).
Function da1469x_sleep_config() should be called during startup to configure PDC entries needed for wakeup functionality.
=> hal: renesas: Add sleep code

smartbond/cmac/rand.h, smartbond/cmac/shm.c, smartbond/cmac/shm.h
CMAC isr will now just call cmac_rng_req() to request host to provide
TRNG data instead of doing this in isr as this could result in a
deadlock due to TRNG isr not being called while we are still waiting
in CMAC isr.
=>  hal: renesas: Fix CMAC trng requests 

smartbond/da1469x_hal/da1469x_sleep.c
This commit should fix the followings:
1. XTAL32M should be selected when the system clock is not RC32M. Switching from/to PLL can only be done when XTAL32M is the system clock.
2. Acquiring PD_SYS with no load should be done when the system enters the WFI state and not the normal sleep state.
=> hal: renesas: Fix clock restoration after sleep

smartbond/da1469x_hal/da1469x_clock.c, smartbond/da1469x_hal/da1469x_clock.h, smartbond/da1469x_hal/da1469x_sleep.c
This commit should deal with the following topics:
1. Fix the way we wait for the PLL to lock. Entering the WFI state should be replaced by __WFE as it might happen that PLL lock ISR is fired right after evaluating the PLL lock bit which should result in stucking in the WFI state (no other interrupts should be expected at that moment to wakeup the application core).
2. Remove the PLL wait to lock API as switching to PLL requires that PLL be locked. Waiting for PLL to lock will be done silently when switching to PLL is requested.
3. Introduce an API to check if PLL is enabled and an API that should be used to check if the DIV1 clock path is used by a peripheral. The latter should also be used to check if USB is active and clocked by PLL such that disabling PLL is not allowed.
=> hal: renesas: Update PLL clock API

zephyr/module.yml
Update version and sha for new CMAC library with RCX lp_clk support enabled.
=> Update to new CMAC library

zephyr/module.yml
This fixes issue with incorrect sleep clock accuracy set for RCX.
=> Update CMAC library

drivers/ra/CMakeLists.txt
change name for Renesas Security IP on RA8 from RSIP7 to RSIP-E51A follow latest HWM
=> hal: renesas: ra: correct configuration name for r_sce follow HWM

zephyr/ra/ra_cfg/fsp_cfg/r_canfd_cfg.h
Update new values ​​for AFL rule count configuration based on Zephyr CAN driver update
Impacted files:
- zephyr/ra/ra_cfg/fsp_cfg/r_canfd_cfg.h
=> hal: renesas: ra: update r_canfd configuration

drivers/ra/README, drivers/ra/fsp/src/bsp/mcu/all/bsp_rom_registers.c
FSP does not set the option setting memory if
CONFIG_SOC_OPTION_SETTING_MEMORY is enabled.
This change is to keep it compatible with the existing RA4M1 implementation.
=> hal: renesas: bsp: Allows custom implementation of option setting memory

zephyr/ra/ra_cfg/fsp_cfg/bsp/ra2a1/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra2l1/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4e2/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4m1/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4m2/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4m3/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra4w1/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6e1/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6e2/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m1/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m2/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m3/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m4/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m5/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8d1/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8m1/bsp_clock_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8t1/bsp_clock_cfg.h
To simplify the DeviceTree notation, we have introduced macros
that derive BSP macro definitions from DeviceTree values.
The clock settings were rewritten by it.
=> hal: renesas: Replace the BSP clock settings with new macros.

drivers/ra/CMakeLists.txt, drivers/ra/README, drivers/ra/fsp/inc/api/r_display_api.h, drivers/ra/fsp/inc/api/r_external_irq_api.h, drivers/ra/fsp/inc/api/r_mipi_dsi_api.h, drivers/ra/fsp/inc/instances/r_glcdc.h, drivers/ra/fsp/inc/instances/r_icu.h, drivers/ra/fsp/inc/instances/r_mipi_dsi.h, drivers/ra/fsp/inc/instances/r_mipi_phy.h, drivers/ra/fsp/src/bsp/mcu/all/bsp_sdram.c, drivers/ra/fsp/src/bsp/mcu/all/bsp_sdram.h, drivers/ra/fsp/src/r_glcdc/r_glcdc.c, drivers/ra/fsp/src/r_icu/r_icu.c, drivers/ra/fsp/src/r_mipi_dsi/r_mipi_dsi.c, drivers/ra/fsp/src/r_mipi_phy/r_mipi_phy.c, zephyr/ra/portable/bsp_common.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m2/bsp_mcu_family_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra6m3/bsp_mcu_family_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8d1/bsp_mcu_family_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8m1/bsp_mcu_family_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/bsp/ra8t1/bsp_mcu_family_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/r_glcdc_cfg.h, zephyr/ra/ra_cfg/fsp_cfg/r_mipi_dsi_cfg.h
- Add support for SDRAM on EK-RA8D1
- Add support for GLCDC driver
- Add support for MIPI-DSI driver
=> hal: renesas: ra: add support for display driver on EK-RA8D1

drivers/rz/CMakeLists.txt, drivers/rz/fsp/inc/api/r_mhu_api.h, drivers/rz/fsp/inc/instances/rzg/r_mhu_ns.h, drivers/rz/fsp/src/rzg/r_mhu_ns/r_mhu_ns.c, zephyr/rz/rz_cfg/fsp_cfg/rzg/r_mhu_ns_cfg.h
=> hal: renesas: rz: Initial support for IPM

drivers/rz/CMakeLists.txt, drivers/rz/fsp/inc/api/r_i2c_master_api.h, drivers/rz/fsp/inc/instances/rzg/r_riic_master.h, drivers/rz/fsp/src/rzg/r_riic_master/r_riic_master.c, zephyr/rz/rz_cfg/fsp_cfg/rzg/r_riic_master_cfg.h
=> hal: renesas: rz: Initial support for I2C

drivers/ra/README, drivers/ra/fsp/inc/instances/r_flash_hp.h
Move the place to store bsp from .code_in_ram section to .ramfunc section
=> hal: renesas: ra: modify BSP_PLACE_IN_SECTION to .ramfunc section

drivers/rz/CMakeLists.txt, drivers/rz/fsp/inc/api/r_external_irq_api.h, drivers/rz/fsp/inc/instances/rzg/r_intc_irq.h, drivers/rz/fsp/inc/instances/rzg/r_intc_nmi.h, drivers/rz/fsp/src/rzg/r_intc_irq/r_intc_irq.c, drivers/rz/fsp/src/rzg/r_intc_nmi/r_intc_nmi.c, zephyr/rz/rz_cfg/fsp_cfg/rzg/r_intc_irq_cfg.h, zephyr/rz/rz_cfg/fsp_cfg/rzg/r_intc_nmi_cfg.h
Initial HAL support for Interrupt Control
=> hal: renesas: rzg: Initial support for Interrupt Control

drivers/rz/CMakeLists.txt, drivers/rz/fsp/inc/instances/rzg/r_gpt.h, drivers/rz/fsp/src/rzg/r_gpt/r_gpt.c, zephyr/rz/rz_cfg/fsp_cfg/rzg/r_gpt_cfg.h
=> hal: renesas: rz: Initial support for PWM

zephyr/rz/rz_cfg/fsp_cfg/bsp/rzg3s/bsp_clock_cfg.h
Support to get clock frequency from device tree
=> hal: renesas: rz: Initial support for Clock Control

zephyr/ra/ra_cfg/fsp_cfg/r_glcdc_cfg.h
This PR to enable GLCDC color correction function, support for:
- display_set_brightness
- display_set_constract
=> hal: renesas: ra: extend support for display color correction

drivers/CMakeLists.txt
zephyr_library() is a CMake function used in Zephyr's build system to define and manage a Zephyr library.
This option will separate the hal_renesas with other zephyr library make it easier to add customize build option.
=> hal: CMakeLists: Add zephyr_library() define to hal_reneas

drivers/ra/fsp/inc/api/r_comparator_api.h
Since the PR Migrate FSP 5.8.0 (#79) lacks the Comparator patch, this PR aims to add it.
The PR contains Comparator patch: #77
=> hal: renesas: ra: Add the Comparator patch for the migration of FSP 5.8.0

zephyr/ra/ra_cfg/fsp_cfg/r_flash_hp_cfg.h
Modify the name `renesas,programming_enable` into `programming_enable` in `r_flash_hp_cfg.h`
=> hal: renesas: ra: Rename the 'programming_enable' property for flash-hp

smartbond/cmac/mbox.c, smartbond/da1469x_hal/da1469x_trimv.c
Add define guards around the min definition so it does not colled with the upstream one.
=> cmac, da1469x_hal: add define guards around min
